[2015-26-Aug 13:40:25] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 80, in resolve_template
    return loader.get_template(template, using=self.using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: registration/login.html
[2015-26-Aug 13:41:05] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/views.py", line 51, in login
    auth_login(request, form.get_user())
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 117, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 26, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/models.py", line 1110, in create_usersettings
    from helpdesk.settings import DEFAULT_USER_SETTINGS
ImportError: No module named settings
[2015-26-Aug 13:42:31] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:42:40] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:42:48] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/views.py", line 51, in login
    auth_login(request, form.get_user())
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 117, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 26, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/models.py", line 1110, in create_usersettings
    from settings import DEFAULT_USER_SETTINGS
ImportError: cannot import name DEFAULT_USER_SETTINGS
[2015-26-Aug 13:45:52] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:45:54] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:46:01] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:47:53] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/urls.py", line 27, in <module>
    (r'^accounts/login/',  login),
NameError: name 'login' is not defined
[2015-26-Aug 13:48:08] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/urls.py", line 29, in <module>
    (r'^accounts/login/',  login),
NameError: name 'login' is not defined
[2015-26-Aug 13:48:09] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/urls.py", line 29, in <module>
    (r'^accounts/login/',  login),
NameError: name 'login' is not defined
[2015-26-Aug 13:48:27] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/Library/Python/2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 112, in get_callable
    if submod and not module_has_submodule(import_module(parentmod), submod):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named tola
[2015-26-Aug 13:48:45] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 74, in profile
    obj = get_object_or_404(UserProfile, user=request.user)
NameError: global name 'UserProfile' is not defined
[2015-26-Aug 13:50:30] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:50:33] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:50:35] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:50:42] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:50:47] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:50:57] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:51:05] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:53:30] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'picker' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:54:01] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'picker' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:56:16] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:56:29] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:56:46] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:56:59] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 04:55:18] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 04:55:18] WARNING [django.request:170] Not Found: /favicon.ico
[2015-27-Aug 05:02:40] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 05:50:49] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 05:50:54] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 05:51:06] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 49, in documentation
    getDocumentation = Documentation.objects.all()
NameError: global name 'Documentation' is not defined
[2015-27-Aug 05:52:35] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 06:17:12] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 06:19:13] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.object.get(user=request.user)
AttributeError: type object 'UserProfile' has no attribute 'object'
[2015-27-Aug 06:19:33] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:21:02] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:21:19] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:24:31] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:30:44] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:02:48] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:05:31] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:09:49] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(name=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:10:26] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(name=str(request.user))
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:11:07] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:21:09] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 09:01:40] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 09:06:40] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:49:11] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:52:40] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:54:15] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk.helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:58:24] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 575, in reverse
    key)
NoReverseMatch: u'helpdesk' is not a registered namespace
[2015-27-Aug 10:11:33] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 76, in dashboard
    queue__in=request.user.queuemembership.queues.all(),
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no queuemembership.
[2015-27-Aug 10:12:57] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 77, in dashboard
    queue__in=request.user.queuemembership.queues.all(),
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no queuemembership.
[2015-27-Aug 10:14:13] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 85, in dashboard
    if limit_queues_by_user:
NameError: global name 'limit_queues_by_user' is not defined
[2015-27-Aug 10:14:56] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 97, in dashboard
    if limit_queues_by_user:
NameError: global name 'limit_queues_by_user' is not defined
[2015-27-Aug 10:15:30] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'load_helpdesk_settings' is not a valid tag library: ImportError raised loading helpdesk.templatetags.load_helpdesk_settings: cannot import name settings
[2015-27-Aug 10:17:12] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1547, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 1011, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'load_helpdesk_settings'
[2015-27-Aug 10:17:40] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'endwith'
[2015-27-Aug 10:18:07] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_rss_user' with arguments '(u'glind',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 10:19:09] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 10:20:56] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'trans'
[2015-27-Aug 10:39:01] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 10:42:41] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 10:43:37] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 867, in create_ticket
    if helpdesk_settings.HELPDESK_STAFF_ONLY_TICKET_OWNERS:
NameError: global name 'helpdesk_settings' is not defined
[2015-27-Aug 10:47:04] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 876, in create_ticket
    if request.user.usersettings.settings.get('use_email_as_submitter', False) and request.user.email:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usersettings.
[2015-27-Aug 10:47:43] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 887, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'bootstrap' is not a valid tag library: Template library bootstrap not found, tried django.templatetags.bootstrap,django.contrib.staticfiles.templatetags.bootstrap,django.contrib.admin.templatetags.bootstrap,rest_framework.templatetags.bootstrap,django_tables2.templatetags.bootstrap,crispy_forms.templatetags.bootstrap,floppyforms.templatetags.bootstrap,django_extensions.templatetags.bootstrap,mathfilters.templatetags.bootstrap,import_export.templatetags.bootstrap,helpdesk.templatetags.bootstrap
[2015-27-Aug 10:48:29] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 887, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'bootstrap'
[2015-27-Aug 10:56:05] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 800, in ticket_list
    ticket_paginator = paginator.Paginator(ticket_qs, request.user.usersettings.settings.get('tickets_per_page') or 20)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usersettings.
[2015-27-Aug 10:57:01] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 842, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 10:57:52] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 842, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 11:01:07] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 842, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: project/base.html
[2015-27-Aug 11:22:18] WARNING [django.request:170] Not Found: /accounts/login/
[2015-27-Aug 11:22:22] WARNING [django.request:170] Not Found: /accounts/login/
[2015-27-Aug 11:22:33] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 11:23:27] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 872, in create_ticket
    ticket = form.save(user=request.user)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/forms.py", line 288, in save
    files=files,
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/lib.py", line 57, in send_templated_mail
    from helpdesk.settings import HELPDESK_EMAIL_SUBJECT_TEMPLATE
ImportError: No module named settings
[2015-27-Aug 11:26:40] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 250, in view_ticket
    'active_users': users,
UnboundLocalError: local variable 'users' referenced before assignment
[2015-27-Aug 11:28:42] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'bootstrap' is not a valid tag library: Template library bootstrap not found, tried django.templatetags.bootstrap,django.contrib.staticfiles.templatetags.bootstrap,django.contrib.admin.templatetags.bootstrap,rest_framework.templatetags.bootstrap,django_tables2.templatetags.bootstrap,crispy_forms.templatetags.bootstrap,floppyforms.templatetags.bootstrap,django_extensions.templatetags.bootstrap,mathfilters.templatetags.bootstrap,import_export.templatetags.bootstrap,helpdesk.templatetags.bootstrap
[2015-27-Aug 11:29:14] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 11:29:57] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1028, in do_if
    nodelist = parser.parse(('endif',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 11:30:24] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 12:36:38] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/edit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 859, in edit_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'bootstrap' is not a valid tag library: Template library bootstrap not found, tried django.templatetags.bootstrap,django.contrib.staticfiles.templatetags.bootstrap,django.contrib.admin.templatetags.bootstrap,rest_framework.templatetags.bootstrap,django_tables2.templatetags.bootstrap,crispy_forms.templatetags.bootstrap,floppyforms.templatetags.bootstrap,django_extensions.templatetags.bootstrap,mathfilters.templatetags.bootstrap,import_export.templatetags.bootstrap,helpdesk.templatetags.bootstrap
[2015-27-Aug 12:37:19] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/edit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 859, in edit_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'bootstrap'
[2015-27-Aug 12:38:31] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/update/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 347, in update_ticket
    comment = loader.get_template_from_string(comment).render(Context(context))
AttributeError: 'module' object has no attribute 'get_template_from_string'
[2015-27-Aug 12:48:30] ERROR [django.request:256] Internal Server Error: /helpdesk/settings/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 1171, in user_settings
    s = request.user.usersettings
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usersettings.
[2015-27-Aug 15:09:05] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 837, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_kb_index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 15:12:35] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/kb.py", line 27, in index
    'helpdesk_settings': helpdesk_settings,
NameError: global name 'helpdesk_settings' is not defined
[2015-27-Aug 15:12:59] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/kb.py", line 26, in index
    'kb_categories': category_list
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'load_helpdesk_settings' is not a valid tag library: ImportError raised loading helpdesk.templatetags.load_helpdesk_settings: cannot import name settings
[2015-27-Aug 15:13:46] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/kb.py", line 26, in index
    'kb_categories': category_list
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1547, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 1011, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'load_helpdesk_settings'
[2015-27-Aug 16:01:41] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 882, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: '"Dashboard"'
[2015-27-Aug 17:40:38] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
