[2015-26-Aug 13:40:25] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 80, in resolve_template
    return loader.get_template(template, using=self.using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: registration/login.html
[2015-26-Aug 13:41:05] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/views.py", line 51, in login
    auth_login(request, form.get_user())
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 117, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 26, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/models.py", line 1110, in create_usersettings
    from helpdesk.settings import DEFAULT_USER_SETTINGS
ImportError: No module named settings
[2015-26-Aug 13:42:31] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:42:40] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:42:48] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/views.py", line 51, in login
    auth_login(request, form.get_user())
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 117, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 26, in update_last_login
    user.save(update_fields=['last_login'])
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Library/Python/2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/models.py", line 1110, in create_usersettings
    from settings import DEFAULT_USER_SETTINGS
ImportError: cannot import name DEFAULT_USER_SETTINGS
[2015-26-Aug 13:45:52] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:45:54] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:46:01] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:47:53] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/urls.py", line 27, in <module>
    (r'^accounts/login/',  login),
NameError: name 'login' is not defined
[2015-26-Aug 13:48:08] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/urls.py", line 29, in <module>
    (r'^accounts/login/',  login),
NameError: name 'login' is not defined
[2015-26-Aug 13:48:09] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/urls.py", line 29, in <module>
    (r'^accounts/login/',  login),
NameError: name 'login' is not defined
[2015-26-Aug 13:48:27] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/Library/Python/2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 112, in get_callable
    if submod and not module_has_submodule(import_module(parentmod), submod):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named tola
[2015-26-Aug 13:48:45] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 74, in profile
    obj = get_object_or_404(UserProfile, user=request.user)
NameError: global name 'UserProfile' is not defined
[2015-26-Aug 13:50:30] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:50:33] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:50:35] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:50:42] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:50:47] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:50:57] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:51:05] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /login/
[2015-26-Aug 13:53:30] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'picker' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:54:01] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'picker' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:56:16] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:56:29] ERROR [django.request:256] Internal Server Error: /login/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-26-Aug 13:56:46] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-26-Aug 13:56:59] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 04:55:18] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 04:55:18] WARNING [django.request:170] Not Found: /favicon.ico
[2015-27-Aug 05:02:40] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 05:50:49] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 05:50:54] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 05:51:06] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 49, in documentation
    getDocumentation = Documentation.objects.all()
NameError: global name 'Documentation' is not defined
[2015-27-Aug 05:52:35] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 06:17:12] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 06:19:13] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.object.get(user=request.user)
AttributeError: type object 'UserProfile' has no attribute 'object'
[2015-27-Aug 06:19:33] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:21:02] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:21:19] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:24:31] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 76, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 06:30:44] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:02:48] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:05:31] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:09:49] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(name=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:10:26] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(name=str(request.user))
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:11:07] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 07:21:09] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 09:01:40] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-27-Aug 09:06:40] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:49:11] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:52:40] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:54:15] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk.helpdesk_dashboard' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 09:58:24] ERROR [django.request:256] Internal Server Error: /documentation
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 53, in documentation
    return render(request, 'documentation.html', {'getDocumentation': getDocumentation})
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 575, in reverse
    key)
NoReverseMatch: u'helpdesk' is not a registered namespace
[2015-27-Aug 10:11:33] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 76, in dashboard
    queue__in=request.user.queuemembership.queues.all(),
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no queuemembership.
[2015-27-Aug 10:12:57] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 77, in dashboard
    queue__in=request.user.queuemembership.queues.all(),
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no queuemembership.
[2015-27-Aug 10:14:13] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 85, in dashboard
    if limit_queues_by_user:
NameError: global name 'limit_queues_by_user' is not defined
[2015-27-Aug 10:14:56] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 97, in dashboard
    if limit_queues_by_user:
NameError: global name 'limit_queues_by_user' is not defined
[2015-27-Aug 10:15:30] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'load_helpdesk_settings' is not a valid tag library: ImportError raised loading helpdesk.templatetags.load_helpdesk_settings: cannot import name settings
[2015-27-Aug 10:17:12] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1547, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 1011, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'load_helpdesk_settings'
[2015-27-Aug 10:17:40] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'endwith'
[2015-27-Aug 10:18:07] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_rss_user' with arguments '(u'glind',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 10:19:09] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 10:20:56] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'trans'
[2015-27-Aug 10:39:01] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 10:42:41] ERROR [django.request:256] Internal Server Error: /helpdesk/dashboard/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 119, in dashboard
    'basic_ticket_stats': basic_ticket_stats,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 10:43:37] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 867, in create_ticket
    if helpdesk_settings.HELPDESK_STAFF_ONLY_TICKET_OWNERS:
NameError: global name 'helpdesk_settings' is not defined
[2015-27-Aug 10:47:04] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 876, in create_ticket
    if request.user.usersettings.settings.get('use_email_as_submitter', False) and request.user.email:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usersettings.
[2015-27-Aug 10:47:43] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 887, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'bootstrap' is not a valid tag library: Template library bootstrap not found, tried django.templatetags.bootstrap,django.contrib.staticfiles.templatetags.bootstrap,django.contrib.admin.templatetags.bootstrap,rest_framework.templatetags.bootstrap,django_tables2.templatetags.bootstrap,crispy_forms.templatetags.bootstrap,floppyforms.templatetags.bootstrap,django_extensions.templatetags.bootstrap,mathfilters.templatetags.bootstrap,import_export.templatetags.bootstrap,helpdesk.templatetags.bootstrap
[2015-27-Aug 10:48:29] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 887, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'bootstrap'
[2015-27-Aug 10:56:05] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 800, in ticket_list
    ticket_paginator = paginator.Paginator(ticket_qs, request.user.usersettings.settings.get('tickets_per_page') or 20)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usersettings.
[2015-27-Aug 10:57:01] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 842, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 10:57:52] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 842, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 11:01:07] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 842, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: project/base.html
[2015-27-Aug 11:22:18] WARNING [django.request:170] Not Found: /accounts/login/
[2015-27-Aug 11:22:22] WARNING [django.request:170] Not Found: /accounts/login/
[2015-27-Aug 11:22:33] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 11:23:27] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 872, in create_ticket
    ticket = form.save(user=request.user)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/forms.py", line 288, in save
    files=files,
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/lib.py", line 57, in send_templated_mail
    from helpdesk.settings import HELPDESK_EMAIL_SUBJECT_TEMPLATE
ImportError: No module named settings
[2015-27-Aug 11:26:40] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 250, in view_ticket
    'active_users': users,
UnboundLocalError: local variable 'users' referenced before assignment
[2015-27-Aug 11:28:42] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'bootstrap' is not a valid tag library: Template library bootstrap not found, tried django.templatetags.bootstrap,django.contrib.staticfiles.templatetags.bootstrap,django.contrib.admin.templatetags.bootstrap,rest_framework.templatetags.bootstrap,django_tables2.templatetags.bootstrap,crispy_forms.templatetags.bootstrap,floppyforms.templatetags.bootstrap,django_extensions.templatetags.bootstrap,mathfilters.templatetags.bootstrap,import_export.templatetags.bootstrap,helpdesk.templatetags.bootstrap
[2015-27-Aug 11:29:14] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 11:29:57] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1028, in do_if
    nodelist = parser.parse(('endif',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'naturaltime'
[2015-27-Aug 11:30:24] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 254, in view_ticket
    'SHOW_SUBSCRIBE': SHOW_SUBSCRIBE,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-27-Aug 12:36:38] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/edit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 859, in edit_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'bootstrap' is not a valid tag library: Template library bootstrap not found, tried django.templatetags.bootstrap,django.contrib.staticfiles.templatetags.bootstrap,django.contrib.admin.templatetags.bootstrap,rest_framework.templatetags.bootstrap,django_tables2.templatetags.bootstrap,crispy_forms.templatetags.bootstrap,floppyforms.templatetags.bootstrap,django_extensions.templatetags.bootstrap,mathfilters.templatetags.bootstrap,import_export.templatetags.bootstrap,helpdesk.templatetags.bootstrap
[2015-27-Aug 12:37:19] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/edit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 859, in edit_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'bootstrap'
[2015-27-Aug 12:38:31] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/2/update/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 347, in update_ticket
    comment = loader.get_template_from_string(comment).render(Context(context))
AttributeError: 'module' object has no attribute 'get_template_from_string'
[2015-27-Aug 12:48:30] ERROR [django.request:256] Internal Server Error: /helpdesk/settings/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 1171, in user_settings
    s = request.user.usersettings
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 462, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usersettings.
[2015-27-Aug 15:09:05] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 837, in ticket_list
    search_message=search_message,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'helpdesk_kb_index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[2015-27-Aug 15:12:35] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/kb.py", line 27, in index
    'helpdesk_settings': helpdesk_settings,
NameError: global name 'helpdesk_settings' is not defined
[2015-27-Aug 15:12:59] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/kb.py", line 26, in index
    'kb_categories': category_list
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'load_helpdesk_settings' is not a valid tag library: ImportError raised loading helpdesk.templatetags.load_helpdesk_settings: cannot import name settings
[2015-27-Aug 15:13:46] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/kb.py", line 26, in index
    'kb_categories': category_list
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1547, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 1011, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'load_helpdesk_settings'
[2015-27-Aug 16:01:41] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-helpdesk/htdocs/helpdesk/views/staff.py", line 882, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: '"Dashboard"'
[2015-27-Aug 17:40:38] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 18:20:15] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-27-Aug 18:26:21] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 80, in profile
    form = RegistrationForm(request.POST or None, instance=obj, initial={'username': request.user})
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/forms.py", line 42, in __init__
    super(RegistrationForm, self).__init__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/forms.py", line 110, in __init__
    super(UserChangeForm, self).__init__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 320, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 130, in model_to_dict
    opts = instance._meta
AttributeError: 'QuerySet' object has no attribute '_meta'
[2015-27-Aug 18:26:54] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 10:09:33] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 10:14:34] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 10:18:21] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 10:22:58] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 10:24:13] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 10:53:20] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 11:01:16] WARNING [django.request:170] Not Found: /helpdesk/help/context/
[2015-28-Aug 11:26:12] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 11:30:14] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/md/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/kb.py", line 36, in category
    'items': items,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'humanize' is not a valid tag library: Template library humanize not found, tried django.templatetags.humanize,django.contrib.staticfiles.templatetags.humanize,django.contrib.admin.templatetags.humanize,rest_framework.templatetags.humanize,django_tables2.templatetags.humanize,crispy_forms.templatetags.humanize,floppyforms.templatetags.humanize,django_extensions.templatetags.humanize,mathfilters.templatetags.humanize,import_export.templatetags.humanize,helpdesk.templatetags.humanize
[2015-28-Aug 11:31:17] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/1/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/kb.py", line 45, in item
    'helpdesk_settings': helpdesk_settings,
NameError: global name 'helpdesk_settings' is not defined
[2015-28-Aug 11:32:12] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/1/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/kb.py", line 44, in item
    'item': item
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'markdown_deux_tags' is not a valid tag library: Template library markdown_deux_tags not found, tried django.templatetags.markdown_deux_tags,django.contrib.staticfiles.templatetags.markdown_deux_tags,django.contrib.admin.templatetags.markdown_deux_tags,rest_framework.templatetags.markdown_deux_tags,django_tables2.templatetags.markdown_deux_tags,crispy_forms.templatetags.markdown_deux_tags,floppyforms.templatetags.markdown_deux_tags,django_extensions.templatetags.markdown_deux_tags,mathfilters.templatetags.markdown_deux_tags,import_export.templatetags.markdown_deux_tags,helpdesk.templatetags.markdown_deux_tags
[2015-28-Aug 11:32:41] ERROR [django.request:256] Internal Server Error: /helpdesk/kb/1/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/kb.py", line 44, in item
    'item': item
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'markdown'
[2015-28-Aug 14:10:19] WARNING [django.request:170] Not Found: /blog
[2015-28-Aug 14:11:00] ERROR [django.request:256] Internal Server Error: /helpdesk/blog/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/blog.py", line 16, in index
    return render_to_response('helpdesk/hackpad.html',RequestContext(request, {'hackpad': hackpad}))
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: helpdesk/hackpad.html
[2015-28-Aug 14:11:44] ERROR [django.request:256] Internal Server Error: /helpdesk/blog/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/blog.py", line 16, in index
    return render_to_response('blog/base.html',RequestContext(request, {'hackpad': hackpad}))
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'endblock'
[2015-28-Aug 14:20:02] ERROR [django.request:256] Internal Server Error: /helpdesk/blog/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/blog.py", line 17, in index
    return render_to_response('blog/base.html',RequestContext(request, {'hackpad': hackpad}))
NameError: global name 'hackpad' is not defined
[2015-28-Aug 14:53:51] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 14:55:21] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 14:58:20] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    form = RegistrationForm(request.POST or None, instance=obj, initial={'username': request.user})
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/forms.py", line 42, in __init__
    super(RegistrationForm, self).__init__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/forms.py", line 110, in __init__
    super(UserChangeForm, self).__init__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 320, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 130, in model_to_dict
    opts = instance._meta
AttributeError: 'QuerySet' object has no attribute '_meta'
[2015-28-Aug 14:58:49] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user=1)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 15:07:34] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 78, in profile
    obj = UserProfile.objects.get(user=1)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 15:10:25] ERROR [django.request:256] Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/project/views.py", line 79, in profile
    obj = UserProfile.objects.get(user__username=request.user)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: UserProfile matching query does not exist.
[2015-28-Aug 15:14:36] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-28-Aug 15:16:18] WARNING [django.request:170] Not Found: /accounts/login/
[2015-28-Aug 15:17:03] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-28-Aug 15:17:14] WARNING [django.request:170] Not Found: /accounts/profile/
[2015-31-Aug 10:38:01] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/staff.py", line 882, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 207, in render
    c = self.get_render(context)
  File "/Library/Python/2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 109, in get_render
    helper = helper.resolve(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 839, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [helper] in u'\n\n\n\n\n    \n    \n        \n            \n                \n                \n\n<tr>\n    <th><label for="id_queue">Queue:</label></th>\n    <td>\n        \n\n        <select name="queue" required id="id_queue">\n\t<option value="">--------</option>\n\t<option value="1">Priority</option>\n</select>\n\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_title">Summary of the problem:</label></th>\n    <td>\n        \n\n        <input type="text" name="title" required maxlength="100" id="id_title" size="60">\n\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_submitter_email">Submitter E-Mail Address:</label></th>\n    <td>\n        \n\n        <input type="text" name="submitter_email" value="glind@mercycorps.org" id="id_submitter_email" size="60">\n\n        <br /><span class="helptext">This e-mail address will receive copies of all public updates to this ticket.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_body">Description of Issue:</label></th>\n    <td>\n        \n\n        <textarea name="body" required rows="15" cols="47" id="id_body"></textarea>\n\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_assigned_to">Case owner:</label></th>\n    <td>\n        \n\n        <select name="assigned_to" id="id_assigned_to">\n\t<option value="">--------</option>\n\t<option value="1">glind</option>\n</select>\n\n        <br /><span class="helptext">If you select an owner other than yourself, they&#39;ll be e-mailed details of this ticket immediately.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_priority">Priority:</label></th>\n    <td>\n        \n\n        <select name="priority" id="id_priority">\n\t<option value="1">1. Critical</option>\n\t<option value="2">2. High</option>\n\t<option value="3" selected="selected">3. Normal</option>\n\t<option value="4">4. Low</option>\n\t<option value="5">5. Very Low</option>\n</select>\n\n        <br /><span class="helptext">Please select a priority carefully. If unsure, leave it as &#39;3&#39;.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_due_date_year">Due on:</label></th>\n    <td>\n        \n\n        <select id="id_due_date_year" name="due_date_year">\n<option value="0">---</option>\n<option value="2015">2015</option>\n<option value="2016">2016</option>\n<option value="2017">2017</option>\n<option value="2018">2018</option>\n<option value="2019">2019</option>\n<option value="2020">2020</option>\n<option value="2021">2021</option>\n<option value="2022">2022</option>\n<option value="2023">2023</option>\n<option value="2024">2024</option>\n</select>\n<select id="id_due_date_month" name="due_date_month">\n<option value="0">---</option>\n<option value="1">January</option>\n<option value="2">February</option>\n<option value="3">March</option>\n<option value="4">April</option>\n<option value="5">May</option>\n<option value="6">June</option>\n<option value="7">July</option>\n<option value="8">August</option>\n<option value="9">September</option>\n<option value="10">October</option>\n<option value="11">November</option>\n<option value="12">December</option>\n</select>\n<select id="id_due_date_day" name="due_date_day">\n<option value="0">---</option>\n<option value="1">1</option>\n<option value="2">2</option>\n<option value="3">3</option>\n<option value="4">4</option>\n<option value="5">5</option>\n<option value="6">6</option>\n<option value="7">7</option>\n<option value="8">8</option>\n<option value="9">9</option>\n<option value="10">10</option>\n<option value="11">11</option>\n<option value="12">12</option>\n<option value="13">13</option>\n<option value="14">14</option>\n<option value="15">15</option>\n<option value="16">16</option>\n<option value="17">17</option>\n<option value="18">18</option>\n<option value="19">19</option>\n<option value="20">20</option>\n<option value="21">21</option>\n<option value="22">22</option>\n<option value="23">23</option>\n<option value="24">24</option>\n<option value="25">25</option>\n<option value="26">26</option>\n<option value="27">27</option>\n<option value="28">28</option>\n<option value="29">29</option>\n<option value="30">30</option>\n<option value="31">31</option>\n</select>\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_attachment">Attach File:</label></th>\n    <td>\n        \n\n        \n<input type="file" name="attachment" id="id_attachment">\n\n        <br /><span class="helptext">You can attach a file such as a document or screenshot to this ticket.</span>\n        \n    </td>\n</tr>\n\n\n            \n        \n        \n    \n\n\n'
[2015-31-Aug 10:38:02] WARNING [django.request:170] Not Found: /favicon.ico
[2015-31-Aug 10:40:13] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/staff.py", line 883, in create_ticket
    'form': form,
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 207, in render
    c = self.get_render(context)
  File "/Library/Python/2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 109, in get_render
    helper = helper.resolve(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 839, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [helper] in u'\n\n\n\n\n    \n    \n        \n            \n                \n                \n\n<tr>\n    <th><label for="id_queue">Queue:</label></th>\n    <td>\n        \n\n        <select name="queue" required id="id_queue">\n\t<option value="">--------</option>\n\t<option value="1">Priority</option>\n</select>\n\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_title">Summary of the problem:</label></th>\n    <td>\n        \n\n        <input type="text" name="title" required maxlength="100" id="id_title" size="60">\n\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_submitter_email">Submitter E-Mail Address:</label></th>\n    <td>\n        \n\n        <input type="text" name="submitter_email" value="glind@mercycorps.org" id="id_submitter_email" size="60">\n\n        <br /><span class="helptext">This e-mail address will receive copies of all public updates to this ticket.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_body">Description of Issue:</label></th>\n    <td>\n        \n\n        <textarea name="body" required rows="15" cols="47" id="id_body"></textarea>\n\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_assigned_to">Case owner:</label></th>\n    <td>\n        \n\n        <select name="assigned_to" id="id_assigned_to">\n\t<option value="">--------</option>\n\t<option value="1">glind</option>\n</select>\n\n        <br /><span class="helptext">If you select an owner other than yourself, they&#39;ll be e-mailed details of this ticket immediately.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_priority">Priority:</label></th>\n    <td>\n        \n\n        <select name="priority" id="id_priority">\n\t<option value="1">1. Critical</option>\n\t<option value="2">2. High</option>\n\t<option value="3" selected="selected">3. Normal</option>\n\t<option value="4">4. Low</option>\n\t<option value="5">5. Very Low</option>\n</select>\n\n        <br /><span class="helptext">Please select a priority carefully. If unsure, leave it as &#39;3&#39;.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_due_date_year">Due on:</label></th>\n    <td>\n        \n\n        <select id="id_due_date_year" name="due_date_year">\n<option value="0">---</option>\n<option value="2015">2015</option>\n<option value="2016">2016</option>\n<option value="2017">2017</option>\n<option value="2018">2018</option>\n<option value="2019">2019</option>\n<option value="2020">2020</option>\n<option value="2021">2021</option>\n<option value="2022">2022</option>\n<option value="2023">2023</option>\n<option value="2024">2024</option>\n</select>\n<select id="id_due_date_month" name="due_date_month">\n<option value="0">---</option>\n<option value="1">January</option>\n<option value="2">February</option>\n<option value="3">March</option>\n<option value="4">April</option>\n<option value="5">May</option>\n<option value="6">June</option>\n<option value="7">July</option>\n<option value="8">August</option>\n<option value="9">September</option>\n<option value="10">October</option>\n<option value="11">November</option>\n<option value="12">December</option>\n</select>\n<select id="id_due_date_day" name="due_date_day">\n<option value="0">---</option>\n<option value="1">1</option>\n<option value="2">2</option>\n<option value="3">3</option>\n<option value="4">4</option>\n<option value="5">5</option>\n<option value="6">6</option>\n<option value="7">7</option>\n<option value="8">8</option>\n<option value="9">9</option>\n<option value="10">10</option>\n<option value="11">11</option>\n<option value="12">12</option>\n<option value="13">13</option>\n<option value="14">14</option>\n<option value="15">15</option>\n<option value="16">16</option>\n<option value="17">17</option>\n<option value="18">18</option>\n<option value="19">19</option>\n<option value="20">20</option>\n<option value="21">21</option>\n<option value="22">22</option>\n<option value="23">23</option>\n<option value="24">24</option>\n<option value="25">25</option>\n<option value="26">26</option>\n<option value="27">27</option>\n<option value="28">28</option>\n<option value="29">29</option>\n<option value="30">30</option>\n<option value="31">31</option>\n</select>\n        \n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_attachment">Attach File:</label></th>\n    <td>\n        \n\n        \n<input type="file" name="attachment" id="id_attachment">\n\n        <br /><span class="helptext">You can attach a file such as a document or screenshot to this ticket.</span>\n        \n    </td>\n</tr>\n\n\n            \n        \n        \n    \n\n\n'
[2015-31-Aug 10:43:21] ERROR [django.request:256] Internal Server Error: /helpdesk/tickets/submit/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/glind/Dropbox/PythonApps/tola-help/htdocs/helpdesk/views/staff.py", line 883, in create_ticket
    'helper': form.helper,
AttributeError: 'TicketForm' object has no attribute 'helper'
